# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MapRecorder' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'EncryptedCoreData', :git => 'https://github.com/project-imas/encrypted-core-data.git'
  # Pods for MapRecorder

  target 'MapRecorderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MapRecorderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
